crds:
  enabled: true

replicaCount: 3
podDisruptionBudget:
  enabled: true

config:
  apiVersion: controller.config.cert-manager.io/v1alpha1
  kind: ControllerConfiguration
  enableGatewayAPI: true

prometheus:
  servicemonitor:
    enabled: true

webhook:
  replicaCount: 3
  podDisruptionBudget:
    enabled: true

cainjector:
  replicaCount: 3
  podDisruptionBudget:
    enabled: true
