- name: Kernel settings
  block:
    - name: Setup kernel module settings
      ansible.builtin.copy:
        content: |
          overlay
          br_netfilter
        dest: /etc/modules-load.d/k8s.conf
        mode: "0644"
      with_items:
        - "{{ users }}"
    - name: Load kernel modules
      community.general.modprobe:
        name: "{{ item }}"
        state: present
      with_items:
        - overlay
        - br_netfilter
    - name: Set kernel params
      ansible.posix.sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        sysctl_set: true
        state: present
        reload: true
        ignoreerrors: true
      with_dict: "{{ containerd_sysctl_config }}"

- name: Install containerd
  block:
    - name: Add gpg key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
    - name: Add Docker apt repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
    - name: Update apt repository
      ansible.builtin.apt:
        update_cache: true
    - name: Install containerd
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - containerd.io
