apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scoreserver-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ictsc/ictsc-regalia-release.git
    path: {{ .Values.env }}
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: scoreserver
  syncPolicy:
{{- if ne .Values.env "dev" }}
    automated:
      prune: true
      selfHeal: true
{{- end }}
