apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scoreserver-application
spec:
  source:
    repoURL: https://github.com/ictsc/ictsc-regalia-release.git
    path: {{ .Values.layer }}
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: scoreserver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
