{{- $cookie_secret := randAlphaNum 32 | b64enc | quote }}

{{- $secret := lookup "v1" "Secret" .Release.Namespace "oauth2-proxy-secret" }}
{{- if $secret }}
  {{- $secret_data = index $secret.data "cookie-secret" }}
{{- end -}}

{{- $client_secret := "" }}

{{- $secret := lookup "v1" "Secret" .Release.Namespace "scoreserver-client" }}
{{- if $secret }}
  {{- $client_secret := index $secret.data "client-secret" }}
{{- else }}
  {{- println "# Could not find scoreserver-client secret" }}
{{- end -}}


apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
type: Opaque
data:
  cookie-secret: {{ $cookie_secret }}
  client-secret: {{ $client_secret }}
