apiVersion: apps/v1
kind: Deployment
metadata:
  name: scoreserver-frontend
  labels:
    app.kubernetes.io/name: scoreserver-frontend
    app.kubernetes.io/part-of: scoreserver
    app.kubernetes.io/component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: scoreserver-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scoreserver-frontend
        app.kubernetes.io/part-of: scoreserver
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: scoreserver
          image: ghcr.io/ictsc/ictsc-regalia/frontend:latest
          livenessProbe:
            initialDelaySeconds: 10
            grpc:
              port: 8080
          resources:
            limits:
              memory: 128Mi
              cpu: "1"
            requests:
              memory: 64Mi
              cpu: 200m
