{{- $secret_data := randAlphaNum .Values.length | b64enc | quote }}

{{- $secret := lookup "v1" "Secret" .Release.Namespace .Release.Name }}
{{- if $secret }}
  {{- $secret_data = index $secret.data .Values.key }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data:
  {{ required "A valid key is required." .Values.key }}: {{ $secret_data }}
