config:
  issuer: http://dex.dex:5556
  connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: (tbd)
        clientSecret: "{{ .Env.CLIENT_SECRET }}"
        redirectURI: https://dex.drove.ictsc.net/callback
        orgs:
          - name: ictsc
            teams:
              - Admins
              - ictsc2024
  staticClients:
    - id: dex-client
      secret: "{{ .Env.CLIENT_SECRET }}"
      name: dex-client
      redirectURIs:
        - http://localhost:8000
        - http://localhost:18000
