config:
  issuer: https://dex.drove.ictsc.net
  connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: "{{ .Env.CLIENT_ID }}"
        clientSecret: "{{ .Env.CLIENT_SECRET }}"
        redirectURI: https://dex.drove.ictsc.net/callback
        orgs:
          - name: ictsc
            teams:
              - Admins
              - ictsc2024
  staticClients:
    - id: dex-client
      secret: "{{ .Env.CLIENT_SECRET }}"
      name: dex-client
      redirectURIs:
        - http://localhost:8000
        - https://contest.ictsc.net/_oauth
        - https://traefik.drove.ictsc.net/_oauth
        - https://ceph.drove.ictsc.net/_oauth
        - https://hubble.drove.ictsc.net/_oauth
        - https://postgres.drove.ictsc.net/_oauth
        - https://k8s-dashboard.drove.ictsc.net/_oauth
        - https://grafana.drove.ictsc.net/callback
    - id: dex-scoreserver-client
      secret: "{{ .Env.SCORESERVER_CLIENT_SECRET }}"
      name: scoreserver-client
      redirectURIs:
        - http://localhost:6000/oauth2/callback
        - https://contest-admin.ictsc.net/oauth2/callback
