config:
  issuer: https://dex.drove.ictsc.net
  connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: (tbd)
        clientSecret: "{{ .Env.CLIENT_SECRET }}"
        redirectURI: https://dex.drove.ictsc.net/callback
        orgs:
          - name: ictsc
            teams:
              - Admins
              - ictsc2024
  staticClients:
    - id: dex-client
      secret: "{{ .Env.CLIENT_SECRET }}"
      name: dex-client
      redirectURIs:
        - http://localhost:8000
        - http://localhost:18000
        - https://contest-dev.ictsc.net/_oauth
        - https://traefik.drove.ictsc.net/_oauth
        - https://ceph.drove.ictsc.net/_oauth
        - https://hubble.drove.ictsc.net/_oauth
        - https://postgres.drove.ictsc.net/_oauth
        - https://phpmyadmin.drove.ictsc.net/_oauth
