# yaml-language-server: $schema=https://raw.githubusercontent.com/traefik/traefik-helm-chart/refs/heads/master/traefik/values.schema.json
deployment:
  replicas: 2

providers:
  kubernetesGateway:
    enabled: false

logs:
  access:
    enabled: true

metrics:
  addInternals: true
  prometheus:
    service:
      enabled: true
    disableAPICheck: true
    serviceMonitor:
      enabled: true

ports:
  websecure:
    http3:
      enabled: true
