# yaml-language-server: $schema=https://raw.githubusercontent.com/traefik/traefik-helm-chart/refs/heads/master/traefik/values.schema.json
deployment:
  replicas: 2

ingressRoute:
  dashboard:
    enabled: true
  healthcheck:
    enabled: true

providers:
  kubernetesGateway:
    enabled: false

metrics:
  addInternals: true
  prometheus:
    service:
      enabled: true
    disableAPICheck: true
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true

ports:
  websecure:
    http3:
      enabled: true
