# yaml-language-server: $schema=https://raw.githubusercontent.com/traefik/traefik-helm-chart/refs/heads/master/traefik/values.schema.json
deployment:
  replicas: 2

providers:
  kubernetesGateway:
    enabled: false

logs:
  access:
    enabled: true

metrics:
  addInternals: true
  prometheus:
    service:
      enabled: true
    disableAPICheck: true
    serviceMonitor:
      enabled: true

additionalArguments:
  - "--api.insecure=true"

ports:
  websecure:
    http3:
      enabled: true

extraObjects:
  # ダッシュボード公開用のService
  - apiVersion: v1
    kind: Service
    metadata:
      name: traefik-api
    spec:
      type: ClusterIP
      selector:
        app.kubernetes.io/name: traefik
      ports:
        - port: 80
          name: traefik
          targetPort: 9000
          protocol: TCP
  # HTTPをHTTPSにリダイレクトするための設定
  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: https-redirect
    spec:
      redirectScheme:
        scheme: https
  - apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      name: catch-all-http
    spec:
      entryPoints:
        - web
      routes:
        - kind: Rule
          match: HostRegexp(`^.+$`)
          priority: -10000
          middlewares:
            - name: https-redirect
          # ここで指定したサービスは使われない
          services:
            - kind: TraefikService
              name: api@internal
