users:
  - name: "ictsc"
    uid: "1011"
    password: "{{ ansible_sudo_pass }}"

# netplanロール用
netplan_remove_existing: false
netplan_enabled: true
netplan_config_file: /etc/netplan/60-ansible-config.yaml
netplan_renderer: networkd

# インストールするKubernetesのバージョン
k8s_install_version: v1.34
