# netplanロール用
netplan_configuration:
  network:
    version: 2
    ethernets:
      eth0:
        addresses:
          - "{{ ipv6 }}/{{ ipv6_prefix_len + 8 }}"
        nameservers:
          addresses:
            - 2001:e42::1
            - 2001:e42::2
      eth1:
        addresses:
          - "{{ internal_ip }}/24"
          - "{{ internal_ipv6 }}/{{ ipv6_prefix_len + 8 }}"

# k8s_joinロール用
k8s_join_flag: --control-plane --certificate-key {{ hostvars[groups['control_plane'][0]]['certs'] }}
