# netplanロール用
netplan_configuration:
  network:
    version: 2
    ethernets:
      eth1:
        addresses:
          - 192.168.100.{{groups["router"].index(inventory_hostname)}}/24

# k8s_installロール用
# join時にtaintを付与するため、kubeletのインストール時に設定
kubelet_extra_args: --register-with-taints unusableKey=:NoSchedule
