# netplanロール用
netplan_configuration:
  network:
    version: 2
    ethernets:
      eth1:
        addresses:
          - 192.168.100.{{groups["router"].index(inventory_hostname)}}/24

# k3s_joinロール用
k3s_join_type: agent
k3s_join_flag: --node-taint unusableKey=:NoSchedule
