apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forward-auth-application
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-200"
    argocd-image-updater.argoproj.io/image-list: >-
      forward-auth=ghcr.io/ictsc/traefik-forward-auth:latest
    argocd-image-updater.argoproj.io/forward-auth.update-strategy: digest
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ictsc/ictsc-drove.git
    path: manifest/infrastructure/forward-auth
    targetRevision: main
    plugin:
      env:
        - name: ENABLE_LOOKUP
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: forward-auth
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
