name: traefik-dashboard
domain: traefik.drove-dev.ictsc.net
routes:
  - match: HOST(`traefik.drove-dev.ictsc.net`)
    services:
      - kind: TraefikService
        name: dashboard@internal
  - match: HOST(`traefik.drove-dev.ictsc.net`) && PathPrefix(`/api`)
    services:
      - kind: TraefikService
        name: api@internal
