apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-login-application
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ictsc/ictsc-drove.git
    path: manifest/basement/kube-login
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
