apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scoreserver-root-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ictsc/ictsc-drove.git
    path: manifest/user/scoreserver
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: scoreserver
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
