repoServer:
  extraContainers:
    - name: helmfile-plugin
      image: ghcr.io/logica0419/argocd-helmfile-plugin:v1.1.1
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
      env:
        - name: ENV_NAME
          value: prod
