{{- range $i, $resource := .Values.resources -}}
{{- if ne $i 0 }}
---
{{- end }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ required "A valid name is required." .name }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ coalesce .kind $.Values.defaults.kind }}
    name: {{ .name }}
  minReplicas: {{ coalesce .minReplicas $.Values.defaults.minReplicas }}
  maxReplicas: {{ coalesce .maxReplicas $.Values.defaults.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: {{ coalesce .targetCPUAverageValue $.Values.defaults.targetCPUAverageValue }}
{{- end }}
