- name: Setup keepalived settings
  block:
    - name: Send keepalived.conf
      ansible.builtin.template:
        src: keepalived.conf
        dest: /etc/keepalived/keepalived.conf
        mode: "0644"
    - name: Send keepalived static pod conf
      ansible.builtin.copy:
        src: keepalived.yaml
        dest: /etc/kubernetes/manifests/keepalived.yaml
        mode: "0644"

- name: Setup haproxy settings
  block:
    - name: Send haproxy.cfg
      ansible.builtin.template:
        src: haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        mode: "0644"
    - name: Send haproxy static pod conf
      ansible.builtin.copy:
        src: haproxy.yaml
        dest: /etc/kubernetes/manifests/haproxy.yaml
        mode: "0644"
