{{- range $i, $ingress := .Values.ingresses -}}
{{- if ne $i 0 }}
---
{{- end }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ required "A valid name is required." .name }}-cert
spec:
  secretName: {{ .name }}-cert
  dnsNames:
    - {{ required "A valid domain is required." .domain }}
  issuerRef:
    name: common-issuer
    kind: ClusterIssuer
{{- end }}
