apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ required "A valid name is required." .Values.name }}-route
spec:
  entryPoints:
    - websecure
  routes:
{{- range $i, $resource := .Values.routes -}}
    - match: {{ coalesce .match printf "Host(`%s`)" .Values.domain }}
      kind: Rule
      services:
        - name: {{ required "A valid service is required." .service }}
          port: {{ coalesce .port 80 }}
{{- end }}
  tls:
    secretName: {{ .Values.name }}-cert
