apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ required "A valid name is required." .Values.name }}-route
spec:
  entryPoints:
    - websecure
  routes:
{{- range $i, $route := .Values.routes }}
    - match: {{ coalesce .match (printf "Host(`%s`)" $.Values.domain) }}
      kind: Rule
      services:
        - kind: {{ coalesce .kind "Service" }}
          name: {{ required "A valid service is required." .service }}
{{- if not .kind }}
          port: {{ coalesce .port 80 }}
{{- end }}
{{- end }}
  tls:
    secretName: {{ .Values.name }}-cert
