{{- range $i, $ingress := .Values.ingresses -}}
  {{- if ne $i 0 }}
---
  {{- end }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ required "A valid name is required." .name }}-route
spec:
  entryPoints:
    - websecure
  routes:
  {{- range $i, $route := .routes }}
    - kind: Rule
    {{- if .match }}
      match: {{ printf "Host(`%s`) && %s" $ingress.domain .match }}
    {{- else }}
      match: {{ printf "Host(`%s`)" $ingress.domain }}
    {{- end }}
      services:
        - name: {{ required "A valid service is required." .service }}
          port: {{ coalesce .port 80 }}
          scheme: http
      middlewares:
        - name: compress
          namespace: traefik
    {{- if .auth }}
        - name: forward-auth
          namespace: forward-auth
    {{- end }}
    {{- with .middlewares }}
      {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- end }}
  tls:
    secretName: {{ .name }}-cert
{{- end }}
