- name: Add users
  block:
    - name: Add a new group
      ansible.builtin.group:
        name: "{{ item.name }}"
        state: present
      with_items:
        - "{{ users }}"
    - name: Add a new users
      ansible.builtin.user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        password: "{{ item.password | password_hash('sha512') }}"
        group: "{{ item.name }}"
        shell: /bin/bash
        groups: sudo
        state: present
      with_items:
        - "{{ users }}"
    - name: Create .ssh directory
      ansible.builtin.file:
        path: /home/{{ item.name }}/.ssh/
        state: directory
        owner: "{{ item.name }}"
        group: sudo
        mode: "0700"
      with_items:
        - "{{ users }}"
    - name: Add authorized_key
      ansible.posix.authorized_key:
        user: "{{ item.name }}"
        key: "{{ lookup('file', '../dev/keys') }}"
      with_items:
        - "{{ users }}"
    - name: Add to sudoers
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        line: "{{ item.name }} ALL=(ALL) NOPASSWD:ALL"
      with_items:
        - "{{ users }}"

- name: Apt upgrade
  block:
    - name: Update and Upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: "dist"
    - name: Check if a reboot is needed
      register: common_reboot_required
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: false
    - name: Reboot if kernel was updated
      when: common_reboot_required.stat.exists
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 1200
        test_command: uptime
