prometheus:
  prometheusSpec:
    thanos:
      baseImage: quay.io/thanos/thanos
      version: v0.37.2
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: ceph-block
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
  thanosService:
    enabled: true
