apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-application
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ictsc/ictsc-drove.git
    path: manifest/infrastructure/cert-manager
    targetRevision: main
    plugin: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
