bases:
  - environments.yaml

repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.17.2
    values:
      - env/common/cert-manager.yaml
  - name: local-charts
    chart: ./local
