bases:
  - environments.yaml

repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.17.1
    values:
      - env/common/cert-manager.yaml
  - name: common-issuer
    namespace: cert-manager
    chart: ./issuer
    values:
      - env: "{{ .Environment.Name }}"
  - name: local-charts
    chart: ./local
