apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scoreserver-main-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=ghcr.io/ictsc/ictsc-regalia/scoreserver:latest
    argocd-image-updater.argoproj.io/backend.update-strategy: digest
spec:
  project: default
  source:
    repoURL: https://github.com/ictsc/ictsc-drove.git
    path: manifest/user/scoreserver/main
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: scoreserver
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: scoreserver-backend
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: Deployment
      name: scoreserver-frontend
      jsonPointers:
        - /spec/replicas
