apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scoreserver-main-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=ghcr.io/ictsc/ictsc-regalia/frontend:latest, backend=ghcr.io/ictsc/ictsc-regalia/scoreserver:latest, toolbox=ghcr.io/ictsc/ictsc-regalia/toolbox:latest
    argocd-image-updater.argoproj.io/frontend.update-strategy: digest
    argocd-image-updater.argoproj.io/backend.update-strategy: digest
    argocd-image-updater.argoproj.io/toolbox.update-strategy: digest
spec:
  project: default
  source:
    repoURL: https://github.com/ictsc/ictsc-drove.git
    path: manifest/user/scoreserver/main
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: scoreserver
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
