apiVersion: apps/v1
kind: Deployment
metadata:
  name: scoreserver-backend
  labels:
    app.kubernetes.io/name: scoreserver-backend
    app.kubernetes.io/part-of: scoreserver
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: scoreserver-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scoreserver-backend
        app.kubernetes.io/part-of: scoreserver
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: scoreserver
          image: ghcr.io/ictsc/ictsc-regalia/scoreserver:latest
          args:
            # これprodでどうにかしないといけない
            - --contestant.base-url=https://contest-dev.ictsc.net/api
            - --contestant.http-addr=0.0.0.0:8080
            - --admin.http-addr=0.0.0.0:8081
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: ictsc.ictsc-cluster.credentials.postgresql.acid.zalan.do
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: ictsc.ictsc-cluster.credentials.postgresql.acid.zalan.do
                  key: password
            - name: DB_DSN
              value: postgres://ictsc-cluster.scoreserver.svc.cluster.local:5432/ictscore
            - name: REDIS_URL
              value: redis://redis-haproxy.scoreserver.svc.cluster.local:6379/0
            - name: GROWI_BASE_URL
              value: https://wiki.ictsc.net
            - name: GROWI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: scoreserver-secrets
                  key: growi-api-token
            - name: DISCORD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: scoreserver-secrets
                  key: discord-client-id
            - name: DISCORD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: scoreserver-secrets
                  key: discord-client-secret
            - name: OTEL_TRACES_EXPORTER
              value: none
            - name: OTEL_METRICS_EXPORTER
              value: none
          # livenessProbe:
          #   initialDelaySeconds: 10
          #   grpc:
          #     port: 8081
          resources:
            requests:
              memory: "0"
              cpu: "0"
            limits:
              memory: 128Mi
              cpu: "1"
