apiVersion: v1
kind: Service
metadata:
  name: scoreserver-contestant-api
  labels:
    app.kubernetes.io/name: scoreserver-contestant-api
    app.kubernetes.io/part-of: scoreserver
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: scoreserver-backend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
