apiVersion: v1
kind: Service
metadata:
  name: scoreserver-frontend
  labels:
    app.kubernetes.io/name: scoreserver-frontend
    app.kubernetes.io/part-of: scoreserver
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/name: scoreserver-frontend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
