apiVersion: batch/v1
kind: Job
metadata:
  name: scoreserver-migration
  labels:
    app.kubernetes.io/name: scoreserver-migration
    app.kubernetes.io/part-of: scoreserver
    app.kubernetes.io/component: backend
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scoreserver-migration
        app.kubernetes.io/part-of: scoreserver
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: migration
          image: ghcr.io/ictsc/ictsc-regalia/toolbox:latest
          command:
            - /home/toolbox/scripts/migrate
          env:
            - name: PGHOST
              value: ictsc-cluster.scoreserver.svc.cluster.local
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: ictscore
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: ictsc.ictsc-cluster.credentials.postgresql.acid.zalan.do
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: ictsc.ictsc-cluster.credentials.postgresql.acid.zalan.do
                  key: password
          resources:
            requests:
              memory: "0"
              cpu: "0"
              ephemeral-storage: 5Gi
            limits:
              memory: 1Gi
              cpu: "1"
              ephemeral-storage: 5Gi
