apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: forward-auth
          image: ghcr.io/ictsc/traefik-forward-auth:3.0.0
          ports:
            - containerPort: 4181
          args:
{{- range $i, $domain := .Values.domains }}
            - --cookie-domain={{ . }}
{{- end }}
            - --default-provider=oidc
            - --providers.oidc.issuer-url={{ required "A valid issuer is required." .Values.issuer }}
            - --providers.oidc.client-id=dex-client
            - --providers.oidc.extra-scopes=groups
{{- if .Values.skipJwtBearerTokens }}
            - --skip-jwt-bearer-tokens=true
{{- end }}
{{- if .Values.tokenPropagation }}
            - --token-propagation=bearer
{{- end }}
          env:
            - name: PROVIDERS_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: client-secret
                  name: github-app
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  key: secret
                  name: {{ .Release.Name }}
          resources:
            requests:
              memory: "0"
              cpu: "0"
            limits:
              cpu: 500m
              memory: 512Mi
