{{- $client_secret := "" }}

{{- $secret := lookup "v1" "Secret" .Release.Namespace "github-app" }}
{{- if $secret }}
  {{- $client_secret := index $secret.data "client-secret" }}
{{- else }}
  {{- warn "Could not find github-app secret" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: headlamp-oidc
type: Opaque
data:
  clientID: {{ .Values.clientID | b64enc }}
  clientSecret: {{ $client_secret }}
  issuerURL: {{ .Values.issuerURL | b64enc }}
  scopes: {{ .Values.scopes | b64enc }}
