{{- $client_secret := "" }}

{{- $secret := lookup "v1" "Secret" .Release.Namespace "github-app" }}
{{- if $secret }}
  {{- $client_secret := index $secret.data "client-secret" }}
{{- else }}
  {{- print "Could not find github-app secret" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: headlamp-oidc
type: Opaque
data:
  OIDC_CLIENT_ID: {{ .Values.clientID | b64enc }}
  OIDC_CLIENT_SECRET: {{ $client_secret }}
  OIDC_ISSUER_URL: {{ .Values.issuerURL | b64enc }}
  OIDC_SCOPES: {{ .Values.scopes | b64enc }}
