bases:
  - environments.yaml

repositories:
  - name: stakater
    url: https://stakater.github.io/stakater-charts

releases:
  - name: reloader
    namespace: reloader
    chart: stakater/reloader
    version: 2.2.4
    values:
      - env/common/values.yaml
  - name: local-charts
    chart: ./local
