grafana:
  grafana.ini:
    users:
      home_page: dashboards/
    auth:
      disable_login_form: true
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Viewer
    auth.github:
      enabled: true
      allow_sign_up: true
      auto_login: false
      scopes: user:email,read:org
      auth_url: https://github.com/login/oauth/authorize
      token_url: https://github.com/login/oauth/access_token
      api_url: https://api.github.com/user
      allowed_organizations:
        - ictsc
      role_attribute_path: contains(groups[*], '@ictsc/Admins') && 'GrafanaAdmin' || contains(groups[*], '@ictsc/ictsc2024') && 'Admin' || 'Viewer'

  envValueFrom:
    GF_AUTH_GITHUB_CLIENT_ID:
      secretKeyRef:
        name: github-app
        key: client-id
    GF_AUTH_GITHUB_CLIENT_SECRET:
      secretKeyRef:
        name: github-app
        key: client-secret

  sidecar:
    dashboards:
      annotations:
        folder: Default
      folderAnnotation: folder
      provider:
        foldersFromFilesStructure: true
