grafana:
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_name: Anonymous
      org_role: Viewer
    auth.github:
      enabled: true
      allow_sign_up: true
      auto_login: false
      scopes: user:email,read:org
      auth_url: https://github.com/login/oauth/authorize
      token_url: https://github.com/login/oauth/access_token
      api_url: https://api.github.com/user
      allowed_organizations:
        - ictsc
      org_mapping: "@ictsc/ictsc2024:ICTSC2024:Admin"

  envValueFrom:
    GF_AUTH_GITHUB_CLIENT_ID:
      secretKeyRef:
        name: github-app
        key: client-id
    GF_AUTH_GITHUB_CLIENT_SECRET:
      secretKeyRef:
        name: github-app
        key: client-secret
