nameOverride: kps
fullnameOverride: kps

prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: true
    retention: 30d
    replicas: 2
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ceph-block
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 15Gi

alertmanager:
  alertmanagerSpec:
    replicas: 3
    resources:
      requests:
        cpu: "0"
        memory: "0"
