nameOverride: kps
fullnameOverride: kps

prometheus:
  prometheusSpec:
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Delete
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: true
    enableRemoteWriteReceiver: true
    enableFeatures:
      - exemplar-storage
    retention: 30d
    replicas: 2
    shards: 2

alertmanager:
  alertmanagerSpec:
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Delete
    replicas: 3
    resources:
      requests:
        cpu: "0"
        memory: "0"

kube-state-metrics:
  replicas: 2
