apiVersion: v1
kind: Pod
metadata:
  name: haproxy
  namespace: kube-system
spec:
  containers:
    - name: haproxy
      # renovate:image
      image: "haproxy:3.1.3"
      resources: {}
      livenessProbe:
        failureThreshold: 8
        httpGet:
          host: localhost
          path: /healthz
          port: 8443
          scheme: HTTPS
      volumeMounts:
        - mountPath: /usr/local/etc/haproxy/haproxy.cfg
          name: config
          readOnly: true
  hostNetwork: true
  volumes:
    - hostPath:
        path: /etc/haproxy/haproxy.cfg
        type: File
      name: config
status: {}
