- name: Setup cilium
  block:
    - name: Add Cilium chart repo
      ansible.builtin.shell: |
        helm repo add cilium https://helm.cilium.io/
        helm repo update
      changed_when: false
    - name: Deploy Cilium
      ansible.builtin.shell: |
        helm upgrade --install cilium cilium/cilium --namespace kube-system \
          --set kubeProxyReplacement=true --set k8sServiceHost={{ VIP }} --set k8sServicePort=6443 --set bgpControlPlane.enabled=true
      changed_when: false

- name: Setup BGP
  block:
    - name: Send bgp-config
      ansible.builtin.template:
        src: bgp-config.yaml.j2
        dest: /tmp/bgp-config.yaml
        mode: "0644"
    - name: Apply bgp-config
      ansible.builtin.command: kubectl apply -f /tmp/bgp-config.yaml
      register: ret
      until: ret.rc == 0
      retries: 12
      delay: 5
      changed_when: false
