- name: Add helm's official GPG key
  ansible.builtin.apt_key:
    url: https://helm.baltorepo.com/organization/signing.asc
    state: present

- name: Add helm repository
  ansible.builtin.apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present

- name: Update apt repository
  ansible.builtin.apt:
    update_cache: true

- name: Install helm
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - helm

- name: Add Cilium chart repo
  ansible.builtin.shell: |
    helm repo add cilium https://helm.cilium.io/
    helm repo update
  changed_when: false

- name: Deploy Cilium
  ansible.builtin.command: helm upgrade --install cilium cilium/cilium --namespace kube-system --set bgpControlPlane.enabled=true
  changed_when: false

- name: Send bgp-config
  ansible.builtin.template:
    src: bgp-config.yaml.j2
    dest: /tmp/bgp-config.yaml
    mode: "0644"

- name: Apply bgp-config
  ansible.builtin.command: kubectl apply -f /tmp/bgp-config.yaml
  register: ret
  until: ret.rc == 0
  retries: 12
  delay: 5
  changed_when: false

- name: Restart pods
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o pipefail
      kubectl get pods --all-namespaces -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,HOSTNETWORK:.spec.hostNetwork \
      --no-headers=true | grep '<none>' | awk '{print "-n "$1" "$2}' | xargs -L 1 -r kubectl delete pod
  changed_when: false
  failed_when: false
