bases:
  - environments.yaml

repositories:
  - name: dandydev
    url: https://dandydeveloper.github.io/charts

releases:
  - name: redis
    namespace: scoreserver
    chart: dandydev/redis-ha
    version: 4.35.3
    values:
      - env/common/redis.yaml
