apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
data:
  config.yaml: |
    peers:
      - peer-address: {{ item }}
        peer-asn: 65020
        my-asn: 65021
    address-pools:
      - name: default
        protocol: bgp
        addresses:
          - {{ hostvars[item]['bgp-address'] }}
  with_dict: "{{ groups['bgp_router'] }}"
