ingresses:
  - name: scoreserver
    domain: contest-dev.ictsc.net
    routes:
      - service: scoreserver-frontend
        auth: true
      - service: scoreserver-contestant-api
        match: PathPrefix(`/api`)
        auth: true
        middlewares:
          - name: strip-prefix
            namespace: traefik
