apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack-application
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ictsc/ictsc-drove.git
    path: manifest/monitoring/prometheus-stack
    targetRevision: main
    plugin: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus-stack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
