- name: Install helm
  block:
    - name: Add helm's official GPG key
      ansible.builtin.apt_key:
        url: https://helm.baltorepo.com/organization/signing.asc
        state: present
    - name: Add helm repository
      ansible.builtin.apt_repository:
        repo: deb https://baltocdn.com/helm/stable/debian/ all main
        state: present
    - name: Update apt repository
      ansible.builtin.apt:
        update_cache: true
    - name: Install helm
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - helm

- name: Setup cilium
  block:
    - name: Add Cilium chart repo
      ansible.builtin.shell: |
        helm repo add cilium https://helm.cilium.io/
        helm repo update
      changed_when: false
    - name: Deploy Cilium
      ansible.builtin.shell: |
        helm upgrade --install cilium cilium/cilium --namespace kube-system \
          --set kubeProxyReplacement=true --set k8sServiceHost={{ VIP }} --set k8sServicePort=8443 --set bgpControlPlane.enabled=true
      changed_when: false
    - name: Restart pods
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          set -o pipefail
          kubectl get pods -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,HOSTNETWORK:.spec.hostNetwork \
            --namespace kube-system --no-headers=true | grep '<none>' | awk '{print "-n "$1" "$2}' | xargs -L 1 -r kubectl delete pod
      changed_when: false
      failed_when: false

- name: Setup BGP
  block:
    - name: Send bgp-config
      ansible.builtin.template:
        src: bgp-config.yaml.j2
        dest: /tmp/bgp-config.yaml
        mode: "0644"
    - name: Apply bgp-config
      ansible.builtin.command: kubectl apply -f /tmp/bgp-config.yaml
      register: ret
      until: ret.rc == 0
      retries: 12
      delay: 5
      changed_when: false

- name: Setup ArgoCD
  block:
    - name: Add ArgoCD chart repo
      ansible.builtin.shell: |
        helm repo add argo https://argoproj.github.io/argo-helm
        helm repo update
      changed_when: false
    - name: Copy ArgoCD values file
      ansible.builtin.template:
        src: argocd-vars.yaml.j2
        dest: /tmp/argocd-vars.yaml
        mode: "0644"
    - name: Deploy ArgoCD
      ansible.builtin.command: helm upgrade --install argocd argo/argo-cd --namespace argocd --create-namespace -f /tmp/argocd-vars.yaml --force
      changed_when: false

- name: Create misc resources
  block:
    - name: Apply Hierarchical Namespace Controller
      ansible.builtin.shell: |
        kubectl apply -f https://github.com/kubernetes-sigs/hierarchical-namespaces/releases/download/v1.1.0/default.yaml
      changed_when: false
    - name: Create infrastructure namespace
      ansible.builtin.command: kubectl create namespace infrastructure
      changed_when: false
    - name: Create GitHub App secret
      ansible.builtin.shell: |
        kubectl create secret generic github-app -n infrastructure \
          --from-literal=client-secret="{{ lookup('env', 'GITHUB_APP_CLIENT_SECRET') }}"
      changed_when: false

- name: Apply root application
  block:
    - name: Copy root application
      ansible.builtin.copy:
        src: application.yaml
        dest: /tmp/application.yaml
        mode: "0644"
    - name: Apply root application
      ansible.builtin.shell: |
        kubectl apply -f /tmp/application.yaml
      register: ret
      until: ret.rc == 0
      retries: 12
      delay: 5
      changed_when: false
