- name: Get join command
  delegate_to: "{{ groups['delegate_plane'][0] }}"
  block:
    - name: Get kubeadm cert
      ansible.builtin.command: kubeadm init phase upload-certs --upload-certs
      register: k8s_join_certs
      changed_when: false
    - name: Get join command
      ansible.builtin.command: kubeadm token create --print-join-command
      register: k8s_join_command
      changed_when: false

- name: Join cluster
  ansible.builtin.command: "{{ k8s_join_command.stdout_lines[0] }} {{ k8s_join_flag }} --ignore-preflight-errors all"
  changed_when: false
  failed_when: false
  when: inventory_hostname not in groups['delegate_plane']
