apiVersion: v2
name: headlamp-secret
description: Headlamp secret chart
type: application
version: 0.1.0
icon: https://icttoracon.net/wp-content/uploads/2023/04/favicon-75x75.png
maintainers:
  - name: ictsc
