# yaml-language-server: $schema=https://raw.githubusercontent.com/cilium/cilium/v1.18.2/install/kubernetes/cilium/values.schema.json

k8sServiceHost: auto
k8sClientRateLimit:
  qps: 40
  burst: 50

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: "0"
    memory: "0"

l2announcements:
  enabled: true

cni:
  resources:
    requests:
      cpu: "0"
      memory: "0"

hubble:
  metrics:
    enabled:
      - dns:query
      - drop
      - flow
      - http
      - port-distribution
      - icmp
      - tcp
    serviceMonitor:
      enabled: true

    dashboards:
      enabled: true
      annotations:
        folder: Cilium
  relay:
    enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  ui:
    enabled: true

ipv6:
  enabled: true
kubeProxyReplacement: true

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true

dashboards:
  enabled: true
  annotations:
    folder: Cilium

envoy:
  enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

operator:
  replicas: 2
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  dashboards:
    enabled: true
    annotations:
      folder: Cilium
