# yaml-language-server: $schema=https://raw.githubusercontent.com/cilium/cilium/refs/heads/main/install/kubernetes/cilium/values.schema.json

k8sServiceHost: auto
k8sClientRateLimit:
  qps: 40
  burst: 50

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: "0"
    memory: "0"

l2announcements:
  enabled: true

cni:
  resources:
    requests:
      cpu: "0"
      memory: "0"

hubble:
  metrics:
    enabled:
      - dns:query
      - drop
      - flow
      - flows-to-world
      - httpV2
      - port-distribution
      - icmp
      - tcp
    enableOpenMetrics: true
    serviceMonitor:
      enabled: true

      relabelings: # Out of Syncへの対処
        - sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: node
          action: replace
          replacement: ${1}

    dashboards:
      enabled: true
      annotations:
        folder: Cilium
  relay:
    enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  ui:
    enabled: true
    replicas: 2

ipv6:
  enabled: true
kubeProxyReplacement: true

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true

    relabelings: # Out of Syncへの対処
      - sourceLabels:
          - __meta_kubernetes_pod_node_name
        targetLabel: node
        action: replace
        replacement: ${1}

dashboards:
  enabled: true
  annotations:
    folder: Cilium

envoy:
  enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

      relabelings: # Out of Syncへの対処
        - sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: node
          action: replace
          replacement: ${1}

operator:
  replicas: 2
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  dashboards:
    enabled: true
    annotations:
      folder: Cilium
