# yaml-language-server: https://raw.githubusercontent.com/cilium/cilium/refs/heads/main/install/kubernetes/cilium/values.schema.json

#--set kubeProxyReplacement=true

k8sServiceHost: auto
k8sClientRateLimit:
  qps: 40
  burst: 50

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 0
    memory: 0

l2announcements:
  enabled: true

hubble:
  metrics:
    serviceMonitor:
      enabled: true
    dashboards:
      enabled: true
      annotations:
        folder: Cilium
  relay:
    enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  ui:
    enabled: true
    replicas: 2
