- name: Install K3s
  ansible.builtin.get_url:
    url: https://github.com/k3s-io/k3s/releases/download/v1.26.5+k3s1/k3s
    dest: /usr/local/bin/k3s
    mode: "0755"

- name: Initialize K3s cluster
  when: inventory_hostname in groups['delegate_plane']
  block:
    - name: Create init config
      ansible.builtin.template:
        src: init-config.yaml.j2
        dest: /tmp/init-config.yaml
        mode: "0644"
    - name: Create cluster
      ansible.builtin.command: k3s server --config=/tmp/init-config.yaml
      changed_when: false
      failed_when: false
    - name: Register token
      ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
      register: token
      changed_when: false
      failed_when: false

- name: Join nodes
  when: inventory_hostname not in groups['delegate_plane']
  block:
    - name: Create join config
      ansible.builtin.template:
        src: join-config.yaml.j2
        dest: /tmp/join-config.yaml
        mode: "0644"
    - name: Join cluster
      ansible.builtin.command: k3s {{ k3s_join_command }} --config=/tmp/join-config.yaml
      changed_when: false
      failed_when: false

- name: Setup kube config
  when: inventory_hostname in groups['control_plane']
  block:
    - name: Replace server address in kube config
      ansible.builtin.replace:
        dest: /etc/rancher/k3s/k3s.yaml
        regexp: "^server:"
        replace: "server: https://{{ VIP }}:6443"
    - name: Create .kube directory for registered users
      ansible.builtin.file:
        path: /home/{{ item.name }}/.kube
        state: directory
        owner: "{{ item.name }}"
        mode: "0700"
      with_items:
        - "{{ users }}"
    - name: Copy admin.conf to registered users kube config
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/{{ item.name }}/.kube/config
        remote_src: true
        owner: "{{ item.name }}"
        mode: "0600"
      with_items:
        - "{{ users }}"
    - name: Create .kube directory for root user
      ansible.builtin.file:
        path: /root/.kube
        state: directory
        owner: root
        mode: "0700"
    - name: Copy admin.conf to root kube config
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /root/.kube/config
        remote_src: true
        owner: root
        mode: "0600"
