apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ictsc/ictsc-drove.git
    path: manifest/infrastructure/argocd
    targetRevision: main
    plugin: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: argocd-applicationset-controller
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: Deployment
      name: argocd-notification-controller
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: Deployment
      name: argocd-redis-ha-proxy
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: StatefulSet
      name: argocd-redis-ha-server
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: Deployment
      name: argocd-repo-server
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: Deployment
      name: argocd-server
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
