bases:
  - environments.yaml

repositories:
  - name: argo-cd
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argocd
    namespace: argocd
    chart: argo-cd/argo-cd
    version: 7.6.12
    values:
      - env/common/argocd-application-set.yaml
      - env/common/argocd-controller.yaml
      - env/common/argocd-dex.yaml
      - env/common/argocd-general.yaml
      - env/common/argocd-notifications.yaml
      - env/common/argocd-redis.yaml
      - env/common/argocd-repo-server.yaml
      - env/common/argocd-server.yaml
      - env/{{ .Environment.Name }}/argocd-general.yaml
      - env/{{ .Environment.Name }}/argocd-repo-server.yaml
  - name: autoscaler
    namespace: argocd
    chart: ../../common/autoscaler
    version: 0.1.0
    values:
      - env/common/autoscaler.yaml
  - name: local-charts
    chart: ./local
