- name: Create manifest directory
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    mode: "0755"

- name: Put RBAC config
  ansible.builtin.get_url:
    url: https://kube-vip.io/manifests/rbac.yaml
    dest: /var/lib/rancher/k3s/server/manifests/kube-vip-rbac.yaml
    mode: "0644"

- name: Put kube-vip config
  ansible.builtin.shell: |
    ctr image pull ghcr.io/kube-vip/kube-vip:v0.8.3
    ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:v0.8.3 vip /kube-vip manifest daemonset \
      --interface eth0 --address {{ VIP }} \
      --inCluster --taint --controlplane --services --arp --leaderElection \
      > /var/lib/rancher/k3s/server/manifests/kube-vip.yaml
  changed_when: false
  failed_when: false
