- name: Put kube-vip config
  ansible.builtin.shell: |
    ctr image pull ghcr.io/kube-vip/kube-vip:v0.6.4
    ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:v0.6.4 vip /kube-vip manifest pod \
      --interface eth0 --vip {{ VIP }} \
      --controlplane --arp --leaderElection \
      > /etc/kubernetes/manifests/kube-vip.yaml
  changed_when: false
  failed_when: false
