- name: Put kube-vip config
  ansible.builtin.shell: |
    ctr image pull ghcr.io/kube-vip/kube-vip:v0.8.2
    ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:v0.8.2 vip /kube-vip manifest pod \
      --interface eth0 --vip {{ VIP }} \
      --controlplane --arp --leaderElection \
      > /etc/kubernetes/manifests/kube-vip.yaml
  changed_when: false
  failed_when: false

# https://github.com/kube-vip/kube-vip/issues/684 のワークアラウンド
- name: Attach super-admin.conf to kube-vip
  ansible.builtin.replace:
    dest: "/etc/kubernetes/manifests/kube-vip.yaml"
    regexp: "path: /etc/kubernetes/admin.conf"
    replace: "path: /etc/kubernetes/super-admin.conf"
