apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      uid: loki
      url: "http://loki-gateway.loki.svc.cluster.local:80"
      access: proxy
      isDefault: false
      jsonData:
        {}
