apiVersion: apps/v1
kind: Deployment
metadata:
  name: scoreserver-backend
  labels:
    app.kubernetes.io/name: scoreserver-backend
    app.kubernetes.io/part-of: scoreserver
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: scoreserver-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scoreserver-backend
        app.kubernetes.io/part-of: scoreserver
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: scoreserver
          image: ghcr.io/ictsc/ictsc-regalia/scoreserver:latest
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ictsc.ictsc-cluster.credentials.postgresql.acid.zalan.do
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ictsc.ictsc-cluster.credentials.postgresql.acid.zalan.do
                  key: password
            - name: DB_HOST
              value: ictsc-cluster.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: regalia
          livenessProbe:
            initialDelaySeconds: 10
            grpc:
              port: 8081
          resources:
            limits:
              memory: 128Mi
              cpu: "1"
            requests:
              memory: 64Mi
              cpu: 200m
