apiVersion: apps/v1
kind: Deployment
metadata:
  name: scoreserver-backend
  labels:
    app.kubernetes.io/name: scoreserver-backend
    app.kubernetes.io/part-of: scoreserver
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: scoreserver-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scoreserver-backend
        app.kubernetes.io/part-of: scoreserver
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: scoreserver
          image: ghcr.io/ictsc/ictsc-regalia/scoreserver:latest
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: ictsc.ictsc-cluster.credentials.postgresql.acid.zalan.do
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: ictsc.ictsc-cluster.credentials.postgresql.acid.zalan.do
                  key: password
            - name: DB_DSN
              value: postgres://ictsc-cluster.svc.cluster.local:5432/ictscore
          livenessProbe:
            initialDelaySeconds: 10
            grpc:
              port: 8081
          resources:
            limits:
              memory: 128Mi
              cpu: "1"
            requests:
              memory: 64Mi
              cpu: 200m
