apiVersion: v1
kind: Service
metadata:
  name: scoreserver-admin-api
  labels:
    app.kubernetes.io/name: scoreserver-admin-api
    app.kubernetes.io/part-of: scoreserver
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: scoreserver-backend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scoreserver-backend
  labels:
    app.kubernetes.io/name: scoreserver-backend
    app.kubernetes.io/part-of: scoreserver
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: scoreserver-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scoreserver-backend
        app.kubernetes.io/part-of: scoreserver
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: scoreserver
          image: ghcr.io/ictsc/ictsc-regalia/scoreserver:latest
          env:
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: postgres-app-credential
                  key: dsn
          livenessProbe:
            initialDelaySeconds: 10
            grpc:
              port: 8081
          resources:
            limits:
              memory: 128Mi
              cpu: 1
            requests:
              memory: 64Mi
              cpu: 200m
