apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ictsc/ictsc-drove.git
    path: manifest/infrastructure
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: cilium-operator
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
