# Default values for autoscaler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

resources:
  # スケールしたいリソースを配列で指定
  # - name: my-app-dep             // (required) リソース名
  #   kind: Deployment             // Deployment | StatefulSet
  #   minReplicas: 2
  #   maxReplicas: 100
  #   targetCPUAverageValue: 100m  // HPAが目指す平均CPU使用コア数

# resourcesのフィールドを省略したときに適用されるデフォルト値
defaults:
  kind: Deployment
  minReplicas: 2
  maxReplicas: 100
  targetCPUAverageValue: 100m
