# Default values for autoscaler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

resources:
  # スケールしたいリソースを配列で指定
  # - name: my-app-dep             // (required) リソース名
  #   hpa: false                   // trueの場合HPAとVPA、falseの場合VPAのみが作成される
  #   kind: Deployment             // Deployment | StatefulSet
  #   minReplicas: 2               // 2よりも小さい場合、2に統一される
  #   maxReplicas: 100             // 2よりも小さい場合、2に統一される
  #   targetCPUAverageValue: 100m  // 必ず500m以下にすること VPAが500mで制限をかけるのでHPAがPodを減らしにかかる

# resourcesのフィールドを省略したときに適用されるデフォルト値
defaults:
  hpa: true
  kind: Deployment
  minReplicas: 2
  maxReplicas: 100
  targetCPUAverageValue: 200m
