- name: Create join config
  ansible.builtin.template:
    src: join-config.yaml.j2
    dest: /tmp/join-config.yaml
    mode: "0644"

- name: Join cluster
  ansible.builtin.command: k3s {{ k3s_join_command }} --config=/tmp/join-config.yaml
  changed_when: false
  failed_when: false

- name: Register token
  ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
  register: token
  changed_when: false
  failed_when: false
