bases:
  - environments.yaml

repositories:
  - name: headlamp
    url: https://kubernetes-sigs.github.io/headlamp/

releases:
  - name: headlamp
    namespace: headlamp
    chart: headlamp/headlamp
    version: 0.40.0
    values:
      - env/common/headlamp.yaml
      - env/{{ .Environment.Name }}/headlamp.yaml
  - name: autoscaler
    namespace: headlamp
    chart: ../../common/autoscaler
    version: 0.1.0
    values:
      - env/common/autoscaler.yaml
  - name: ingress
    namespace: headlamp
    chart: ../../common/ingress
    version: 0.1.0
    values:
      - env/{{ .Environment.Name }}/ingress.yaml
  - name: local-charts
    chart: ./local
