apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-proxy
spec:
  forwardAuth:
    address: http://oauth2-proxy-scoreserver.scoreserver.svc.cluster.local:80
    trustForwardHeader: true
    authResponseHeaders:
      - Authorization
      - X-Auth-Request-Access-Token
