bases:
  - environments.yaml

repositories:
  - name: open-telemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts

releases:
  - name: otel-col
    namespace: otel-col
    chart: open-telemetry/opentelemetry-collector
    version: 0.119.0
    values:
      - env/common/otel-col.yaml
  - name: local-charts
    chart: ./local
