replicaCount: 2

config:
  issuer: http://dex.dex:5556

envVars:
  - name: CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: github-app
        key: client-secret

serviceMonitor:
  enabled: true
