apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-apiserver-application
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-200"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ictsc/ictsc-drove.git
    path: manifest/infrastructure/kube-apiserver
    targetRevision: main
    plugin: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
