resources:
  requests:
    cpu: 0
    memory: 0
global:
  defaultResources:
    requests:
        cpu: 0
  proxy:
    resources:
      requests:
        cpu: 0
        memory: 0
  waypoint:
    resources:
      requests:
        cpu: 0
        memory: 0