# wait for ssh connection
- hosts: all
  name: Wait for SSH connection
  gather_facts: false
  roles:
    - wait_ssh

# common setup phase
- hosts: all
  name: Common Setup
  become: true
  roles:
    - common
    - mrlesmithjr.netplan

- hosts: router
  name: BIRD Setup
  become: true
  roles:
    - bird

# containerd setup phase
- hosts: cloud_servers
  name: Containerd Setup
  become: true
  roles:
    - containerd

# kubernetes setup phase
- hosts: control_plane:worker_node
  name: Kubernetes setup
  become: true
  roles:
    - k8s_install

# kubernetes api lb setup phase
- hosts: lb
  name: Kubernetes api lb setup
  become: true
  roles:
    - lb

# kubeadm setup phase
- hosts: delegate_plane
  name: Kubeadm setup
  any_errors_fatal: true
  become: true
  roles:
    - k8s_init
    - cilium
    - argo_cd

# join other control_plane
- hosts: control_plane:worker_node
  name: Join other control_plane
  become: true
  roles:
    - k8s_join
