- name: Private address setup
  hosts: control_plane
  any_errors_fatal: true
  gather_facts: false
  roles:
    - wait_ssh
    - mrlesmithjr.netplan

- name: Common setup
  hosts: all
  any_errors_fatal: true
  become: true
  roles:
    - wait_ssh
    - mrlesmithjr.netplan
    - common
    - containerd
    - k8s_install

- name: Kubernetes API loadbalancer setup
  hosts: control_plane
  any_errors_fatal: true
  become: true
  roles:
    - lb

- name: Kubernetes bootstrap
  hosts: delegate_plane
  any_errors_fatal: true
  become: true
  roles:
    - k8s_init

- name: Join nodes
  hosts: all
  any_errors_fatal: true
  become: true
  roles:
    - k8s_join

- name: Application bootstrap
  hosts: delegate_plane
  any_errors_fatal: true
  become: true
  roles:
    - components
    - kubeconfig
