- name: Wait for SSH connection
  hosts: all
  gather_facts: false
  roles:
    - wait_ssh

- name: Common Setup
  hosts: all
  become: true
  roles:
    - common
    - mrlesmithjr.netplan

- name: BIRD Setup
  hosts: router
  become: true
  roles:
    - bird

- name: Kube-vip Setup
  hosts: control_plane
  become: true
  roles:
    - kube_vip

- name: K3s Setup
  hosts: all
  any_errors_fatal: true
  become: true
  roles:
    - k3s

- name: Components Bootstrap
  hosts: delegate_plane
  become: true
  roles:
    - components
