- name: Wait for SSH connection
  hosts: all
  any_errors_fatal: true
  gather_facts: false
  roles:
    - wait_ssh

- name: Common setup
  hosts: all
  any_errors_fatal: true
  become: true
  roles:
    - common
    - mrlesmithjr.netplan
    - k3s_download

- name: BIRD setup
  hosts: router
  any_errors_fatal: true
  become: true
  roles:
    - bird

- name: K3s bootstrap
  hosts: delegate_plane
  any_errors_fatal: true
  become: true
  roles:
    # kube-vipはバイナリを配布していないので、ひとまずの対応としてcontainerdをインストール
    - containerd
    - kube_vip
    - containerd_remove
    - k3s_init
    - helm
    - cilium

- name: Join control plane
  hosts: control_plane
  any_errors_fatal: true
  become: true
  roles:
    - k3s_join_server

- name: Join worker node
  hosts: worker_node
  any_errors_fatal: true
  become: true
  roles:
    - k3s_join_agent

- name: ArgoCD & application Bootstrap
  hosts: delegate_plane
  any_errors_fatal: true
  become: true
  roles:
    - argocd
    - application
