- name: Wait for SSH connection
  hosts: all
  gather_facts: false
  roles:
    - wait_ssh

- name: Common Setup
  hosts: all
  become: true
  roles:
    - common
    - mrlesmithjr.netplan
    - containerd
    - k8s_install

- name: BIRD Setup
  hosts: router
  become: true
  roles:
    - bird

- name: Kubernetes API Load Balancer Setup
  hosts: control_plane
  become: true
  roles:
    - kube_vip

- name: Kubernetes Bootstrap
  hosts: delegate_plane
  any_errors_fatal: true
  become: true
  roles:
    - k8s_init
    - helm
    - cilium
    - argo_cd

- name: Join Nodes
  hosts: all
  become: true
  roles:
    - k8s_join
