- name: Wait for SSH connection
  hosts: all
  any_errors_fatal: true
  gather_facts: false
  roles:
    - wait_ssh

- name: Common setup
  hosts: all
  any_errors_fatal: true
  become: true
  roles:
    - common
    - mrlesmithjr.netplan
    - containerd
    - k8s_install

- name: BIRD setup
  hosts: router
  any_errors_fatal: true
  become: true
  roles:
    - bird

- name: Kubernetes API Load Balancer Setup
  hosts: control_plane
  any_errors_fatal: true
  become: true
  roles:
    - lb

- name: Kubernetes Bootstrap
  hosts: delegate_plane
  any_errors_fatal: true
  become: true
  roles:
    - k8s_init

- name: Join Nodes
  hosts: all
  any_errors_fatal: true
  become: true
  roles:
    - k8s_join

- name: Kubernetes Bootstrap
  hosts: delegate_plane
  any_errors_fatal: true
  become: true
  roles:
    - components
