- name: Wait for SSH connection
  hosts: all
  gather_facts: false
  roles:
    - wait_ssh

- name: Common Setup
  hosts: all
  become: true
  roles:
    - common
    - mrlesmithjr.netplan

- name: BIRD Setup
  hosts: router
  become: true
  roles:
    - bird

- name: Containerd & K8s Setup
  hosts: control_plane:worker_node
  become: true
  roles:
    - containerd
    - k8s_install

- name: Kubernetes API Load Balancer Setup
  hosts: control_plane
  become: true
  roles:
    - lb

- name: Kubernetes Setup
  hosts: delegate_plane
  any_errors_fatal: true
  become: true
  roles:
    - k8s_init
    - cilium
    - argo_cd

- name: Join Nodes
  hosts: control_plane:worker_node
  become: true
  roles:
    - k8s_join
