- name: Dry-run kubeadm init
  ansible.builtin.command: kubeadm init --dry-run
  register: kubeadm_dry_run
  changed_when: false
  failed_when: false
- name: Run kubeadm init
  when: kubeadm_dry_run.rc == 0 # skip init if already initialized
  block:
    - name: Create kubeadm-config.yaml
      ansible.builtin.template:
        src: kubeadm-config.yaml.j2
        dest: /tmp/kubeadm-config.yaml
        mode: "0644"
    - name: Run kubeadm init
      ansible.builtin.command: kubeadm init --upload-certs --config=/tmp/kubeadm-config.yaml
      changed_when: false

- name: Setup kube config
  block:
    - name: Create .kube directory for registered users
      ansible.builtin.file:
        path: /home/{{ item.name }}/.kube
        state: directory
        owner: "{{ item.name }}"
        mode: "0700"
      with_items:
        - "{{ users }}"
    - name: Copy admin.conf to registered users kube config
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ item.name }}/.kube/config
        remote_src: true
        owner: "{{ item.name }}"
        mode: "0600"
      with_items:
        - "{{ users }}"
    - name: Create .kube directory for root user
      ansible.builtin.file:
        path: /root/.kube
        state: directory
        owner: root
        mode: "0700"
    - name: Copy admin.conf to root kube config
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: true
        owner: root
        mode: "0600"
