- name: Setup ArgoCD
  block:
    - name: Add ArgoCD chart repo
      ansible.builtin.shell: |
        helm repo add argo https://argoproj.github.io/argo-helm
        helm repo update
      changed_when: false
    - name: Copy ArgoCD values file
      ansible.builtin.template:
        src: argocd-vars.yaml.j2
        dest: /tmp/argocd-vars.yaml
        mode: "0644"
    - name: Deploy ArgoCD
      ansible.builtin.command: helm upgrade --install argocd argo/argo-cd --namespace argocd --create-namespace -f /tmp/argocd-vars.yaml --force
      changed_when: false

- name: Apply root application
  block:
    - name: Copy root application
      ansible.builtin.copy:
        src: application.yaml
        dest: /tmp/application.yaml
        mode: "0644"
    - name: Apply root application
      ansible.builtin.shell: |
        kubectl apply -f /tmp/application.yaml
      register: ret
      until: ret.rc == 0
      retries: 12
      delay: 5
      changed_when: false

- name: Create GitHub OAuth secret
  block:
    - name: Create infrastructure namespace
      ansible.builtin.command: kubectl create namespace infrastructure
      changed_when: false
    - name: Create GitHub App secret
      ansible.builtin.shell: |
        kubectl create secret generic github-app -n infrastructure \
          --from-literal=client-secret="{{ lookup('env', 'GITHUB_APP_CLIENT_SECRET') }}"
      changed_when: false
