fullnameOverride: argocd

global:
  logging:
    format: json

configs:
  params:
    server.insecure: true
  cm:
    admin.enabled: false
    controller.diff.server.side: true
    resource.exclusions: |
      - apiGroups:
        - cilium.io
        kinds:
        - CiliumIdentity
        clusters:
        - "*"
    resource.customizations: |
      argoproj.io/Application:
        health.lua: |
          hs = {}
          hs.status = "Progressing"
          hs.message = ""
          if obj.status ~= nil then
            if obj.status.health ~= nil then
              hs.status = obj.status.health.status
              if obj.status.health.message ~= nil then
                hs.message = obj.status.health.message
              end
            end
          end
          return hs
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $github-app:client-id
            clientSecret: $github-app:client-secret
            orgs:
              - name: ictsc
                teams:
                  - Admins
                  - ictsc2024
  rbac:
    policy.csv: |
      g, ictsc:ictsc2024, role:admin
