fullnameOverride: argocd

global:
  logging:
    format: json

configs:
  params.server.insecure: true
  cm:
    admin.enabled: false
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: Iv1.eb9e9a2c66234f5e
            clientSecret: $github-app:client-secret
            orgs:
              - name: ictsc
                teams:
                  - ictsc2024
  rbac:
    policy.csv: |
      g, ictsc:Admins, role:admin
      g, ictsc:ictsc2024, role:readonly
