repoServer:
  replicas: 2
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  clusterRoleRules:
    enabled: true
    rules:
      - apiGroups: [""]
        resources:
          - configmaps
          - secrets
        verbs:
          - get
