repoServer:
  replicas: 2
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  clusterRoleRules:
    enabled: true
    rules:
      - apiGroups: [""]
        resources:
          - configMap
        verbs:
          - get

  volumes:
    - name: helm-replace
      configMap:
        name: helm-replace
        defaultMode: 0777

extraObjects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: helm-replace
    data:
      helm: |-
        #!/bin/bash

        if [[ "$1" == "template" ]]; then
          /usr/local/sbin/helm "$@" --dry-run=server
        else
          /usr/local/sbin/helm "$@"
        fi
