apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ictsc/ictsc-drove.git
    path: manifest/infrastructure/traefik
    targetRevision: main
    plugin: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
