apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-stack-application
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ictsc/ictsc-drove.git
    path: manifest/monitoring/otel-stack
    targetRevision: main
    plugin: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: otel-stack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: cilium.io/v2
      kind: CiliumIdentity
