config:
  issuer: https://dex-admin.drove-dev.ictsc.net
  connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: "{{ .Env.CLIENT_ID }}"
        clientSecret: "{{ .Env.CLIENT_SECRET }}"
        redirectURI: https://dex-admin.drove-dev.ictsc.net/callback
        orgs:
          - name: ictsc
            teams:
              - Admins
  staticClients:
    - id: dex-client
      secret: "{{ .Env.CLIENT_SECRET }}"
      name: dex-client
      redirectURIs:
