config:
  issuer: https://dex.drove-dev.ictsc.net
  connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: Iv1.eb9e9a2c66234f5e
        clientSecret: "{{ .Env.CLIENT_SECRET }}"
        redirectURI: https://dex.drove-dev.ictsc.net/callback
        orgs:
          - name: ictsc
            teams:
              - Admins
              - ictsc2024
  staticClients:
    - id: dex-client
      secret: "{{ .Env.CLIENT_SECRET }}"
      name: dex-client
      redirectURIs:
        - http://localhost:8000
        - http://localhost:18000
        - https://contest-dev.ictsc.net/_oauth
        - https://traefik.drove-dev.ictsc.net/_oauth
        - https://ceph.drove-dev.ictsc.net/_oauth
        - https://hubble.drove-dev.ictsc.net/_oauth
        - https://postgres.drove-dev.ictsc.net/_oauth
        - https://k8s-dashboard.drove-dev.ictsc.net/_oauth
        - https://grafana.drove-dev.ictsc.net/_oauth
    - id: dex-scoreserver-client
      secret: "{{ .Env.SCORESERVER_CLIENT_SECRET }}"
      name: scoreserver-client
      redirectURIs:
        - http://localhost:6000/oauth2/callback
        - https://contest-admin-dev.ictsc.net/oauth2/callback
