config:
  connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: Iv1.eb9e9a2c66234f5e
        clientSecret: "{{ .Env.CLIENT_SECRET }}"
        redirectURI: https://dex.drove-dev.ictsc.net/callback
        orgs:
          - name: ictsc
            teams:
              - Admins
              - ictsc2024
  staticClients:
    - id: dex-client
      secret: "{{ .Env.CLIENT_SECRET }}"
      name: dex-client
      redirectURIs:
        - http://localhost:8000
        - http://localhost:18000
