apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: forward-auth
          image: thomseddon/traefik-forward-auth:latest
          ports:
            - containerPort: 4181
          args:
{{- range $i, $domain := .Values.domains }}
            - --cookie-domain={{ . }}
{{- end }}
            - --default-provider=dex-client
            - --providers.oidc.issuer-url={{ .Values.issuer }}
            - --providers.oidc.client-id=forward-auth
          env:
            - name: PROVIDERS_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: client-secret
                  name: github-app
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  key: secret
                  name: {{ .Release.Name }}
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
