apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}
spec:
  forwardAuth:
    address: http://{{ .Release.Name }}:4181
    authResponseHeaders:
      - X-Forwarded-User
