{{- $secret_data := randAlphaNum 64 | b64enc | quote }}

{{- $secret := lookup "v1" "Secret" .Release.Namespace .Release.Name }}
{{- if $secret }}
  {{- $secret_data = index $secret.data "secret" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data:
  secret: {{ $secret_data }}
