ingresses:
  - name: scoreserver
    domain: contest.ictsc.net
    routes:
      - service: scoreserver-frontend
      - service: scoreserver-contestant-api
        match: PathPrefix(`/api`)
        middlewares:
          - name: strip-prefix
            namespace: traefik
  - name: scoreserver-admin
    domain: contest-admin.ictsc.net
    routes:
      - service: scoreserver-admin-api
        middlewares:
          - name: oauth2-proxy
            namespace: scoreserver
