- name: Add ArgoCD chart repo
  ansible.builtin.shell: |
    helm repo add argo https://argoproj.github.io/argo-helm
    helm repo update
  changed_when: false

- name: Copy ArgoCD values file
  ansible.builtin.copy:
    src: argocd-vars.yaml
    dest: /tmp/argocd-vars.yaml
    mode: "0644"

- name: Deploy ArgoCD
  ansible.builtin.command: helm upgrade --install argocd argo/argo-cd --namespace argocd --create-namespace -f /tmp/argocd-vars.yaml --force
  changed_when: false
