- name: Install argocd
  ansible.builtin.shell: |
    kubectl create namespace argocd
    kubectl apply -n argocd \
    -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  changed_when: false
