name: Ansible

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install Ansible Lint
        run: pip install ansible-lint
      - name: Ansible Lint
        run: ansible-lint -s
