name: Spell Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  spell-check:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Spell Check
        uses: streetsidesoftware/cspell-action@v6
        with:
          incremental_files_only: false
          config: ./dev/cspell/cspell.config.yaml
          verbose: true
