apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: kube-apiserver-route
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`k8s.drove.ictsc.net`)
      services:
        - name: kubernetes
          port: https
          tls: true
  tls:
    secretName: kube-apiserver-cert
    passthrough: true
